import NavBar from '../components/navBar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <NavBar 
      // sendQueryToParent={handleSearchQuery}
      />
        {children}</body>
    </html>
  )
}
