pipeline {
    agent any
    tools {
        nodejs "NodeJS"
    }
    stages {
        stage('Install') {
            steps {
                sh 'npm install'
                dir ('next/news-aggregation') {
                    sh 'npm install'
                }
                dir ('newAPI') {
                    sh 'npm install'
                }
            }
        }
        stage('debug') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }
        stage ('sonarqube') {
            steps {
                script {
                    def scannerHome = tool 'SonarQube';
                    withSonarQubeEnv('newnewtitanium') {
                        sh "${scannerHome}/bin/sonar-scanner"
                    }
                }
            }
        }
        stage('run website') {
            steps {
                sh './Jenkins/start.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './Jenkins/stop.sh'
            }
        }
    }
}
