pipeline {
    agent any
    tools {
        nodejs "NodeJS"
    }
    stages {
        stage('Install') {
            steps {
                sh 'npm install'
            }
        }
        stage('debug') {
            steps {
                sh 'pwd'
                sh 'ls -la'
            }
        }
        stage('run website') {
            steps {
                sh './jenkins/start.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                sh './jenkins/scripts/stop.sh'
            }
        }
    }
}
