apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-aggregation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: news-aggregation
  template:
    metadata:
      labels:
        app: news-aggregation
    spec:
      containers:
      - name: news-aggregation
        image: ghcr.io/nmcc1212/next-app
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: news-aggregation
spec:
  selector:
    app: news-aggregation
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer