pipeline {
    agent any
    tools {
        nodejs "NodeJS"
    }
    stages {
        stage('Install') {
            steps {
                sh 'npm install'
            }
        }
        parrallel {
            stage('Run API') {
                steps {
                    dir('newAPI/src') {
                        sh 'ts-node index.ts'
                    }
                }
            }
            stage('Run Web Site') {
                steps {
                    dir('next/news-aggregation') {
                        sh 'npm run dev'
                    }
                }
            }
        input message: 'Finished using the web site? (Click "Proceed" to continue)'
        }
    }
}
