ALTER TABLE Likes
ADD CONSTRAINT FK_Likes_Post
	FOREIGN KEY (PostID)
	REFERENCES Posts(PostID)
	ON DELETE CASCADE
;
ALTER TABLE Comments
ADD CONSTRAINT FK_Comments_PostID
	FOREIGN KEY (PostID)
	REFERENCES Posts(PostID)
	ON DELETE CASCADE

-- test
SELECT * FROM Posts Where PostID = 251 LIMIT 1000;
SELECT * FROM Likes Where PostID = 251 LIMIT 1000;

DELETE FROM Posts Where PostID = 251;

SELECT * FROM Posts Where PostID = 251 LIMIT 1000;
SELECT * FROM Likes Where PostID = 251 LIMIT 1000;