name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-mongo-api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: nmcc1212
        password: ${{ secrets.GHCR_PAT }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: newAPI/Dockerfile
        push: true
        tags: ghcr.io/nmcc1212/mongo-api:latest