name: omg this is so dumb

on:
  push:
    branches:
      - main

jobs:
  export-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      - name: Deploy to remote host
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.NEWNEWTITANIUM_IP }}
          username: ${{ secrets.NEWNEWTITANIUM_USER }}
          password: ${{ secrets.NEWNEWTITANIUM_PASS }}
          script: |
            cd /home/nial/
            echo ${{ secrets.GHCR_PAT }} > pat.txt